<?php
/**
 * Copyright 2014 Bogdan Ghervan
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
?>
<div class="alert alert-warning alert-exception" role="alert">
    <h3>Oh Snap!</h3>
    <p>
        Apache is denied access to read PAM configuration, which prevents CronKeep from reading the crontab.
        Here's the error we got:
    </p>
    <p>
        <samp>
            <?php echo $e->getMessage() ?>
        </samp>
    </p>
    <p>
        Please head on to the
        <a href="https://github.com/cronkeep/cronkeep/blob/master/INSTALL.md#apache-is-denied-access-to-read-pam-configuration">
            Troubleshooting</a>
        section for the recommended way to clear this error.
    </p>
    <p class="action-items">
        <a href="https://github.com/cronkeep/cronkeep/blob/master/INSTALL.md#apache-is-denied-access-to-read-pam-configuration"
           title="Proceed to Trobleshooting" class="btn btn-warning" type="button">
            Proceed to Troubleshooting</a>
    </p>
</div>
