<div class="row">
	<div class="col-xs-8">
		<h2><?php echo $systemUser->getUsername() ?></h2>
	</div>
	<div class="col-xs-4">
		<div class="btn-toolbar" role="toolbar">
			<button type="button" class="btn btn-primary pull-right job-add" title="Add Job"
					autocomplete="off">
				<span class="glyphicon glyphicon-plus"></span> Add Job
			</button>
		</div>
	</div>
</div>

<div class="panel panel-default panel-crontab">
	<div class="panel-heading">
		<input type="text" class="form-control job-search" autocomplete="off" placeholder="Search">
	</div>

	<div class="empty-search hidden">
		<p>Your search did not match any of the jobs.</p>
		<button type="button" class="btn btn-default job-search-reset">
			<span class="glyphicon glyphicon-arrow-left"></span>
			Start Over
		</button>
	</div>

	<table class="table table-hover table-crontab">
		<thead>		
			<tr>
				<th>Time</th>
				<th>Command</th>
				<th></th>
			</tr>
		</thead>
		<tbody>
			<?php
				foreach ($crontab as $job):
					$classAttr = $job->isPaused() ? ' class="inactive"' : '';
			?>
			<tr data-hash="<?php echo $job->getHash() ?>"<?php echo $classAttr ?>>
				<td data-searchable="1"><?php echo $job->getExpression() ?></td>
				<td data-searchable="1">
					<?php echo $job->getCommand() ?>
					<?php if ($job->getComment()): ?>
						<span class="glyphicon glyphicon-question-sign"
							  data-toggle="tooltip" title="<?php echo $job->getComment() ?>"></span>
					<?php endif; ?>
				</td>
				<td>
					<div class="btn-group pull-right hidden-xs">
						<button type="button" class="btn btn-success job-run" title="Run Job Now"
								data-loading-text="Starting..." autocomplete="off">
							<span class="glyphicon glyphicon-play"></span> Run
						</button>
						<button type="button" class="btn btn-success dropdown-toggle"
								data-toggle="dropdown">
							<span class="caret"></span>
							<span class="sr-only">Toggle Dropdown</span>
						</button>
						<ul class="dropdown-menu" role="menu">
							<li class="menu-item-resume <?php echo $job->isPaused() ? 'show' : 'hidden' ?>">
								<a href="#" title="Resume Job Schedule" class="job-resume">
									<span class="glyphicon glyphicon-repeat"></span> Resume Schedule</a>
							</li>
							<li class="menu-item-pause <?php echo $job->isPaused() ? 'hidden' : 'show' ?>">
								<a href="#" title="Pause Job Schedule" class="job-pause">
									<span class="glyphicon glyphicon-pause"></span> Pause Schedule</a>
							</li>
							<li>
								<a href="#" title="Permanently Delete Job" class="job-confirm-delete">
									<span class="glyphicon glyphicon-remove"></span> Delete</a>
							</li>
						</ul>
					</div>
					<div class="btn-group pull-right visible-xs">
						<button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
							<span class="caret"></span>
						</button>
						<ul class="dropdown-menu" role="menu">
							<li>
								<a href="#" title="Run Job Now" class="job-run">
									<span class="glyphicon glyphicon-play"></span> Run</a>
							</li>
							<li class="menu-item-resume <?php echo $job->isPaused() ? 'show' : 'hidden' ?>">
								<a href="#" title="Resume Job Schedule" class="job-resume">
									<span class="glyphicon glyphicon-repeat"></span> Resume Schedule</a>
							</li>
							<li class="menu-item-pause <?php echo $job->isPaused() ? 'hidden' : 'show' ?>">
								<a href="#" title="Pause Job Schedule" class="job-pause">
									<span class="glyphicon glyphicon-pause"></span> Pause Schedule</a>
							</li>
							<li>
								<a href="#" title="Permanently Delete Job" class="job-confirm-delete">
									<span class="glyphicon glyphicon-remove"></span> Delete</a>
							</li>
						</ul>
					</div>
				</td>
			</tr>
			<?php endforeach; ?>
		</tbody>
	</table>
</div>
<?php echo $view->partial('partials/job-delete.phtml') ?>
<?php echo $view->partial('partials/job-add.phtml') ?>