<div class="row">
	<div class="col-xs-8">
		<h2><?php echo $systemUser->getUsername() ?></h2>
	</div>
	<div class="col-xs-4">
		<button type="button" class="btn btn-primary pull-right job-add" title="Add Job"
				autocomplete="off">
			<span class="glyphicon glyphicon-plus"></span> Add Job
		</button>
	</div>
</div>

<div class="panel panel-default panel-crontab">
	<div class="panel-heading">
		<input type="text" class="form-control job-search" autocomplete="off" placeholder="Search">
	</div>

	<div class="empty-search hidden">
		<p>Your search did not match any of the jobs.</p>
		<button type="button" class="btn btn-default job-search-reset">
			<span class="glyphicon glyphicon-arrow-left"></span>
			Start Over
		</button>
	</div>

	<table class="table table-hover table-crontab">
		<thead>		
			<tr>
				<th>Time</th>
				<th>Command</th>
				<th></th>
			</tr>
		</thead>
		<tbody>
			<?php foreach ($crontab as $job): ?>
				<?php echo $this->partial('partials/job.phtml', array(
					'job' => $job
				)) ?>
			<?php endforeach; ?>
		</tbody>
	</table>
</div>

<?php echo $this->partial('partials/job-delete.phtml') ?>
<?php echo $this->partial('partials/job-add-dialog.phtml', array(
	'simpleForm'   => $simpleForm,
	'advancedForm' => $advancedForm
)) ?>