<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="description" content="Web-based cron manager app">
	<meta name="author" content="Bogdan Ghervan">
	<title>cronkeep</title>
	<link href="assets/css/bootstrap.min.css" rel="stylesheet">
	<link href="assets/css/styles.css" rel="stylesheet">
	<!--[if lt IE 9]>
	  <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
	  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
	<![endif]-->
</head>
<body>
	<!-- Fixed navbar -->
	<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
		<div class="container">
			<div class="navbar-header">
				<a class="navbar-brand" href="#">cronkeep</a>
			</div>
		</div>
	</div>

	<div class="container">
		<?php if (!$isAtCommandAvailable): ?>
			<div class="alert alert-warning alert-dismissible" role="alert">
				<button type="button" class="close" data-dismiss="alert">
					<span aria-hidden="true">&times;</span>
					<span class="sr-only">Close</span>
				</button>
				<h4>Oh Snap!</h4>
				<p>
					<code>at</code> is not available on this system. cronkeep uses this slick
					command	internally to run jobs independently from your web server, whenever
					you hit "Run". <span class="hidden-xs">This means you could restart
					your web server and still have the process running in the background.</span>
					
					<a href="#" class="visible-xs-inline keep-reading">
						Keep reading <span class="glyphicon glyphicon-arrow-right"></span></a>
				</p>
				<?php if ($atCommandErrorOutput == \models\At::ERROR_ACCESS_DENIED): ?>
					<p class="hidden-xs">
						To allow access you should add user
						<code><?php echo $systemUser->getUsername() ?></code> to your
						<code>/etc/at.allow</code> file on a new line. If the file does not
						exist, locate <code>/etc/at.deny</code> and remove the user from there.
						Please be mindful that no whitespace is permitted in either file.
					</p>
				<?php else: ?>
					<p class="hidden-xs">
						Here's the raw output from the command that may help you debug this further:
						<samp class="at-command-error-output">
							<a href="http://www.google.com/#q=<?php echo urlencode($atCommandErrorOutput) ?>"
							   class="alert-link" target="_blank"><?php echo $atCommandErrorOutput ?></a>
						</samp>
					</p>
				<?php endif; ?>
			</div>
		<?php endif; ?>
		
		<div class="alert-area"></div>
		<div><?php echo $content ?></div>
	</div>
	
	<?php if ($vars): ?>
	<script>
		<?php echo $vars ?>
	</script>
	<?php endif; ?>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src="assets/js/bootstrap.min.js"></script>
    <script src="assets/js/highlightRegex.min.js"></script>
    <script src="assets/js/alert.js"></script>
    <script src="assets/js/crontab.js"></script>
    <script src="assets/js/search.js"></script>
    <script src="assets/js/index.js"></script>
</body>

</html>