<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
	<meta name="description" content="Web-based cron manager app">
	<meta name="author" content="Bogdan Ghervan">
	<title>cronkeep</title>
	<link href="assets/css/bootstrap.min.css" rel="stylesheet">
	<link href="assets/css/styles.css" rel="stylesheet">
	<!--[if lt IE 9]>
	  <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
	  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
	<![endif]-->
</head>
<body>
	<!-- Fixed navbar -->
	<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
		<div class="container">
			<div class="navbar-header">
				<a class="navbar-brand" href="#">cronkeep</a>
			</div>
		</div>
	</div>

	<div class="container">
		<?php if (!$isAtCommandAvailable): ?>
			<?php echo $this->partial('partials/alert-at-unavailable.phtml', array(
				'atCommandErrorOutput' => $atCommandErrorOutput,
				'systemUser' => $systemUser
			)) ?>
		<?php endif; ?>
		
		<div class="alert-area"></div>
		<div><?php echo $content ?></div>
	</div>
	
	<?php if ($vars): ?>
	<script>
		<?php echo $vars ?>
	</script>
	<?php endif; ?>
	<script src="assets/js/jquery-1.11.1.min.js"></script>
    <script src="assets/js/jquery.validate.min.js"></script>
    <script src="assets/js/bootstrap.min.js"></script>
    <script src="assets/js/highlightRegex.min.js"></script>
    <script src="assets/js/alert.js"></script>
    <script src="assets/js/crontab.js"></script>
	<script src="assets/js/job-add.js"></script>
    <script src="assets/js/search.js"></script>
    <script src="assets/js/index.js"></script>
</body>

</html>