<div class="modal fade" id="job-add" tabindex="-1" role="dialog" aria-labelledby="job-add-title" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
				<h4 class="modal-title" id="job-add-title">Add Job</h4>
			</div>
			<div class="modal-body">
				<ul class="nav nav-pills" role="tablist">
					<li class="active">
						<a href="#simple" role="tab" data-toggle="pill" data-mode="simple">
							Simple</a>
					</li>
					<li>
						<a href="#advanced" role="tab" data-toggle="pill" data-mode="advanced">
							Advanced</a>
					</li>
				</ul>
				<div class="tab-content">
					<div class="tab-pane active" id="simple">
						<?php echo $this->partial('partials/job-add-simple.phtml', array(
							'form' => $simpleForm
						)) ?>
					</div>
					
					<div class="tab-pane" id="advanced">
						<?php echo $this->partial('partials/job-add-advanced.phtml', array(
							'form' => $advancedForm
						)) ?>
					</div>
				</div>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
				<button type="button" class="btn btn-primary btn-save"
						data-loading-text="Saving...">Save</button>
			</div>
		</div>
	</div>
</div>