<form class="job-add-form" role="form">
	<div class="row">
		<div class="col-md-2">
			<span class="legend">Job Name</span>
		</div>
		<div class="col-md-10">
			<input type="text" class="form-control" autocomplete="off">
		</div>
	</div>
	<div class="row" style="margin-top: 20px;">
		<div class="col-md-2">
			<span class="legend">Time Expression</span>
		</div>
		<div class="col-md-10">
			<input type="text" class="form-control" autocomplete="off" placeholder="">
			<p class="help-block">
				You may peep at this 
				<a href="https://linuxmoz.com/crontab-syntax-tutorial/" target="_blank"
				   title="Crontab Syntax Tutorial With Examples - LinuxMoz">
					tutorial on crons</a> or read
				<a href="http://unixhelp.ed.ac.uk/CGI/man-cgi?crontab+5" target="_blank"
				   title="UNIX man pages : crontab (5)">
					the crontab man page</a> for a full walkthrough.
			</p>
		</div>
	</div>
	<div class="row" style="margin-top: 20px;">
		<div class="col-md-2">
			<span class="legend">Command</span>
		</div>
		<div class="col-md-10">
			<textarea class="form-control" rows="2" id="command"></textarea>
		</div>
	</div>
</form>