<form class="job-add-form" role="form">
	<div class="form-group">
		<span class="legend">Run this command</span>
		<textarea class="form-control" rows="2" id="command"></textarea>
	</div>
	
	<div class="row section-expression">
		<div class="col-md-2">
			<span class="legend">Expression</span>
		</div>
		<div class="col-md-10">
			<div class="input-group expression-part">
				<span class="input-group-addon">Minute</span>
				<input type="text" class="form-control" value="*" required name="minute">
			</div>
			<div class="input-group expression-part">
				<span class="input-group-addon">Hour</span>
				<input type="text" class="form-control" value="*" required name="hour">
			</div>
			<div class="input-group expression-part">
				<span class="input-group-addon">Day of month</span>
				<input type="text" class="form-control" value="*" required name="dayOfMonth">
			</div>
			<div class="input-group expression-part">
				<span class="input-group-addon">Month</span>
				<input type="text" class="form-control" value="*" required name="month">
			</div>
			<div class="input-group expression-part">
				<span class="input-group-addon">Day of week</span>
				<input type="text" class="form-control" value="*" required name="dayOfWeek">
			</div>
		</div>
	</div>
</form>