<?php
/**
 * Copyright 2014 Bogdan Ghervan
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
?>
<div class="modal fade" id="job-edit" tabindex="-1" role="dialog" aria-labelledby="job-edit-title"
     aria-hidden="true" data-hash="<?php echo $hash ?>">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                <h4 class="modal-title" id="job-edit-title">Edit Job</h4>
            </div>
            <div class="modal-body">
                <ul class="nav nav-pills" role="tablist">
                    <?php if ($simpleForm): ?>
                        <li class="active">
                            <a href="#simple-edit" role="tab" data-toggle="pill"
                               data-mode="simple">Simple</a>
                        </li>
                    <?php else: ?>
                        <li class="disabled">
                            <a href="#">Simple</a>
                        </li>
                    <?php endif; ?>
                    <li<?php echo (!$simpleForm) ? ' class="active"' : '' ?>>
                        <a href="#advanced-edit" role="tab" data-toggle="pill"
                           data-mode="advanced">Advanced</a>
                    </li>
                </ul>
                <div class="tab-content">
                    <?php if ($simpleForm): ?>
                        <div class="tab-pane active" id="simple-edit">
                            <?php echo $this->partial('partials/job-simple-form.phtml', array(
                                'hash' => $hash,
                                'form' => $simpleForm
                            )) ?>
                        </div>
                    <?php endif; ?>

                    <div class="tab-pane<?php echo (!$simpleForm) ? ' active' : '' ?>"
                         id="advanced-edit">
                        <?php echo $this->partial('partials/job-advanced-form.phtml', array(
                            'hash' => $hash,
                            'form' => $advancedForm
                        )) ?>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary btn-save" autocomplete="off"
                        data-loading-text="Saving...">Save</button>
            </div>
        </div>
    </div>
</div>
