<?php
/* @var $form \forms\AddJob\SimpleForm */
$form->prepare();
?>
<form class="job-add-form" role="form">
	<div class="row">
		<div class="col-md-2">
			<span class="legend"><?php echo $form->get('name')->getLabel() ?></span>
		</div>
		<div class="col-md-10">
			<?php echo $this->formText($form->get('name')) ?>
		</div>
	</div>
	<div class="row">
		<div class="col-md-2">
			<span class="legend"><?php echo $form->get('command')->getLabel() ?></span>
		</div>
		<div class="col-md-10">
			<?php echo $this->formTextarea($form->get('command')) ?>
		</div>
	</div>
	
	<?php
		/* @var $time \Zend\Form\Fieldset */
		$time = $form->get('time');
	?>
	<div class="row">
		<div class="col-md-2">
			<span class="legend"><?php echo $time->get('picker')->getLabel() ?></span>
		</div>
		<div class="col-md-10">
			<!-- Specific time in the day -->
			<div class="radio radio-time radio-specific-time">
				<label>
					<input type="radio" name="<?php echo $time->get('picker')->getName() ?>"
						   value="specificTime" autocomplete="off">
					Specific time in the day
				</label>
				<ul class="list-unstyled list-specific-time">
					<li>
						<?php echo $this->formNumber($time->get('specificTime')->get('hour')) ?> : 
						<?php echo $this->formNumber($time->get('specificTime')->get('minute')) ?>
					</li>
				</ul>
			</div>

			<!-- Hourly at minute {min} -->
			<div class="radio radio-time radio-every-hour">
				<input type="radio" name="<?php echo $time->get('picker')->getName() ?>"
					   value="everyHour" autocomplete="off">
				<span>
					Every 
					<?php echo $this->formNumber($time->get('everyHour')->get('step')) ?>
					hours at minute
					<?php echo $this->formNumber($time->get('everyHour')->get('minute')) ?>
				</span>
			</div>

			<!-- Every {min} minutes -->
			<div class="radio radio-time radio-every-minute">
				<input type="radio" name="<?php echo $time->get('picker')->getName() ?>"
					   value="everyMinute" autocomplete="off">
				<span>
					Every
					<?php echo $this->formNumber($time->get('everyMinute')->get('step')) ?>
					minutes
				</span>
			</div>
		</div>
	</div>
	
	<?php
		/* @var $repeat \Zend\Form\Fieldset */
		$repeat = $form->get('repeat');
	?>
	<div class="row">
		<div class="col-md-2">
			<span class="legend"><?php echo $repeat->get('picker')->getLabel() ?></span>
		</div>
		<div class="col-md-10">
			<?php echo $this->formSelect($repeat->get('picker')) ?>
		</div>
	</div>

	<!-- Repeat: Weekly -->
	<?php
		/* @var $dayOfWeek \Zend\Form\Element\MultiCheckbox */
		$dayOfWeek = $repeat->get('weekly')->get('dayOfWeek');
	?>
	<div class="row fieldset-weekly hidden">
		<div class="col-md-2"></div>
		<div class="col-md-10">
			<span class="hint"><?php echo $dayOfWeek->getLabel() ?></span>
			<div>
				<div class="btn-group" data-toggle="buttons">
					<?php echo $this->formMultiCheckbox($dayOfWeek) ?>
				</div>
			</div>
		</div>
	</div>

	<!-- Repeat: Monthly -->
	<?php
		/* @var $dayOfMonth \Zend\Form\Element\MultiCheckbox */
		$dayOfMonth = $repeat->get('monthly')->get('dayOfMonth');
	?>
	<div class="row fieldset-monthly hidden">
		<div class="col-md-2"></div>
		<div class="col-md-10">
			<span class="hint"><?php echo $dayOfMonth->getLabel() ?></span>
			<div>
				<div class="btn-group btn-group-day-picker">
					<div class="btn-group" data-toggle="buttons">
						<?php foreach ($dayOfMonth->getValueOptions() as $day): ?>
							<label class="btn btn-default">
								<input type="checkbox" name="<?php echo $dayOfMonth->getName() ?>[]"
									   autocomplete="off" value="<?php echo $day ?>">
								<?php echo $day ?>
							</label>
							<?php if ($day % 7 == 0): ?>
								</div>
								<div class="btn-group" data-toggle="buttons">
							<?php endif; ?>
						<?php endforeach; ?>
					</div>
				</div>
			</div>
		</div>
	</div>

	<!-- Repeat: Yearly -->
	<div class="row fieldset-yearly hidden">
		<div class="col-md-2"></div>
		<div class="col-md-10">
			<div>
				<span class="hint"><?php echo $repeat->get('yearly')->getLabel() ?></span>
				<div class="clearfix">
					<?php echo $this->formSelect($repeat->get('yearly')->get('month')) ?>
					<?php echo $this->formNumber($repeat->get('yearly')->get('day')) ?>
				</div>
			</div>
		</div>
	</div>
</form>