<?php
$weekDays = array('Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat');
$days = range(1, 31);
$months = array(
	1 => 'January', 2 => 'February', 3 => 'March', 4 => 'April',
	5 => 'May', 6 => 'June', 7 => 'July', 8 => 'August', 9 => 'September',
	10 => 'October', 11 => 'November', 12 => 'December'
);
?>
<form class="job-add-form" role="form">
	<div class="row">
		<div class="col-md-2">
			<span class="legend">Job Name</span>
		</div>
		<div class="col-md-10">
			<input type="text" class="form-control" autocomplete="off">
		</div>
	</div>
	<div class="row" style="margin-top: 20px;">
		<div class="col-md-2">
			<span class="legend">Command</span>
		</div>
		<div class="col-md-10">
			<textarea class="form-control" rows="2" id="command"></textarea>
		</div>
	</div>	
	<div class="row section-pick-time">
		<div class="col-md-2">
			<span class="legend">Pick time</span>
		</div>
		<div class="col-md-10">
			<!-- Specific time in the day -->
			<div class="radio radio-time radio-specific-time">
				<label>
					<input type="radio" name="time" value="specific-time" checked autocomplete="off">
					Specific time in the day
				</label>

				<ul class="list-unstyled list-specific-time">
					<li>
						<input type="number" class="form-control input-hour" placeholder="h"
							   maxlength="2" autocomplete="off" min="0" max="23"> :
						<input type="number" class="form-control input-minute" placeholder="m"
							   maxlength="2" autocomplete="off" min="0" max="59">
					</li>
				</ul>
			</div>

			<!-- Hourly at minute {min} -->
			<div class="radio radio-time radio-every-hour">
				<input type="radio" name="time" value="every-hour"
					   autocomplete="off">

				<span>
					Every 
					<input type="number" class="form-control input-recur" maxlength="2"
						   autocomplete="off" disabled value="1" min="1">
					hours at minute
					<input type="number" class="form-control input-minute" maxlength="2"
						   autocomplete="off" disabled value="0" min="0" max="59">
				</span>
			</div>

			<!-- Every {min} minutes -->
			<div class="radio radio-time radio-every-minute">
				<input type="radio" name="time" value="every-minute" autocomplete="off">

				<span>
					Every
					<input type="number" class="form-control input-recur" maxlength="2"
						   autocomplete="off" value="1" disabled min="1">
					minutes
				</span>
			</div>
		</div>
	</div>
	<div class="row section-repeat">
		<div class="col-md-2">
			<span class="legend">Repeat</span>
		</div>
		<div class="col-md-10">
			<select class="form-control repeat" name="repeat" autocomplete="off">
				<option value="daily">Daily</option>
				<option value="weekly">Weekly</option>
				<option value="monthly">Monthly</option>
				<option value="yearly">Yearly</option>
			</select>
		</div>
	</div>

	<!-- Repeat: Weekly -->
	<div class="row row-customize-weekly hidden">
		<div class="col-md-2"></div>
		<div class="col-md-10">
			<span class="hint">Pick day of week</span>
			<div>
				<div class="btn-group" data-toggle="buttons">
					<?php foreach ($weekDays as $weekDay): ?>
						<label class="btn btn-default">
							<input type="checkbox" name="dayOfWeek" autocomplete="off">
							<?php echo $weekDay ?>
						</label>
					<?php endforeach; ?>
				</div>
			</div>
		</div>
	</div>

	<!-- Repeat: Monthly -->
	<div class="row row-customize-monthly hidden">
		<div class="col-md-2"></div>
		<div class="col-md-10">
			<span class="hint">Pick days</span>
			<div>
				<div class="btn-group btn-group-day-picker">
					<div class="btn-group" data-toggle="buttons">
						<?php foreach ($days as $day): ?>
							<label class="btn btn-default">
								<input type="checkbox" name="day" autocomplete="off"
									   value="<?php echo $day ?>">
								<?php echo $day ?>
							</label>
							<?php if ($day % 7 == 0): ?>
								</div>
								<div class="btn-group" data-toggle="buttons">
							<?php endif; ?>
						<?php endforeach; ?>
					</div>
				</div>
			</div>
		</div>
	</div>

	<!-- Repeat: Yearly -->
	<div class="row row-customize-yearly hidden">
		<div class="col-md-2"></div>
		<div class="col-md-10">
			<div>
				<span class="hint">Pick dates</span>
				<div class="clearfix">
					<select class="form-control month pull-left" name="month" autocomplete="off">
						<?php foreach ($months as $i => $month): ?>
							<option value="<?php echo $i ?>"><?php echo $month ?></option>
						<?php endforeach; ?>
					</select>
					<input type="number" maxlength="2" autocomplete="off" value="1"
						   class="form-control input-day pull-left" min="1" max="31">
				</div>
			</div>
		</div>
	</div>
</form>